### ISSUE TITLE
Jest preset doesn't work standalone without build configuration

### ISSUE THREAD

**Issue by constgen** [neutrinojs/neutrino#813]
### Bug

- Neutrino 8.2.2
- Presets: `@neutrinojs/jest` and `@neutrinojs/web` (optionally)
- NPM 4.1.2
- Node 7.7.0
- Windows 8.1
- **What did you do?** - Started `neutrino test`
- **What did you expect to happen?** - all test in `test` folder to run
- **What actually happened, contrary to your expectations?** No test found

### Proposal

Currently `@neutrinojs/jest` can't work by itself if there is no other build preset in the project like `@neutrinojs/web` or `@neutrinojs/react`. This is because this build presets define extensions necessary to Jest to resolve modules. `neutrino test  --use @neutrinojs/jest` reports:

```
No tests found
No files found in C:\Users\cgenchevsky\Desktop\te.
Make sure Jest's configuration does not exclude this directory.
To set up Jest, make sure a package.json file exists.
Jest Documentation: facebook.github.io/jest/docs/configuration.html
Pattern:  - 0 matches
```

If define additional preset it works. `neutrino test  --use @neutrinojs/jest @neutrinojs/web`:

```
 PASS  test\index.test.js

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        2.758s
Ran all test suites.
```

The reason is because build presets define module resolve extenions which are necessary for Jest. Workaround looks like this. Use **.neutrinojs.js**:

```js
module.exports = {
    use: [
        '@neutrinojs/jest',
        function(neutrino){
            let { config, options } = neutrino
        
            config.resolve
                .modules
                    .add('node_modules')
                    .end()
                .extensions
                    .add('.js')
                    .end()
        }
    ]
}
```

But we need to fix this in the Jest preset or Neutrino core.

Proposed solution may be valid also for other testing presets.

This is useful when you want to quickly and easy install Jest infrastructure to projects that didn't use Neutrino.

**Comment by edmorley** [comment]
I think at the moment all of the testing related presets presume there is a build preset being used alongside them (vs the linting presets which work standalone aiui). How common a case do you think it is for there to be no build preset in use?

**Comment by eliperelman** [comment]
Looking at the code for the jest preset in master, and given our reliance now also on the Jest CLI, I think this is fixed in master.

**Comment by eliperelman** [comment]
Yes, I believe this is fixed. Please reopen if testing on master proves otherwise.

**Comment by edmorley** [comment]
Trying locally it still doesn't work for me:

```
$ jest
No tests found
No files found in C:\Users\Ed\src\test-project.
Make sure Jest's configuration does not exclude this directory.
To set up Jest, make sure a package.json file exists.
Jest Documentation: facebook.github.io/jest/docs/configuration.html
Pattern:  - 0 matches
error Command failed with exit code 1.
```

If I manually configure the resolve extensions like so (ie copied from the web preset):
```js
neutrino.config.resolve
  .extensions
    .merge(neutrino.options.extensions.concat('json').map(ext => `.${ext}`));
```

...then it works.

I guess this line should have a fallback if it's not already set?
https://github.com/neutrinojs/neutrino/blob/d48eb35dd093a0d89bb78128ed9f4a26d054154b/packages/jest/src/index.js#L83-L85

**Comment by eliperelman** [comment]
Yeah, makes sense to me.

**Comment by yordis** [comment]
I am replicating CRA (without using Neutrino plugin) and by reverse engineering what Neutrino team did code like this one

https://github.com/neutrinojs/neutrino/blob/6948fc3907879152627445e06a94dfff9d543e2c/packages/web/index.js#L132-L136

Probably would be better to create another preset that does not require that much code. It would be just the entry and the output config.

I truly believe that `web` is doing too much right now and probably is better to extract some of the code out.

**Comment by eliperelman** [comment]
@yordis Feel free to propose some changes in another issue so we can discuss whether we need to split this out in the future.
